### PR TITLE
Dockerise application

### PR DESCRIPTION
**Pull request by romanhaa**
This PR adds instructions to create a Docker image running either the Open Targets Platform or Open Targets Genetics frontend. Choosing between the two applications is done using `--build-arg app={platform,genetics}`. Any value other than `platform` or `genetics` will result in an error during the build process. The respective application is built from source.

Do you see any issues with this? I hope you find it useful.

### CODE REVIEW

**Comment by mbdebian** [comment]
The way we deploy Open Targets Platform web application has two main aspects:
- The application itself, **already** bundled in the corresponding _GitHub release_ as a _vanilla bundle_, but this cannot be used as it is, unless in a development environment.
- The different **contexts** that are shipped together with the web application:
  - **Running context**, this tells the application things like:
    - where to communicate with the underlying Open Targets API
    - which _robots.txt_ profile to use
    - which _customization profile_ it should use
  - **Data Context**, these are data files that are bound to the data release that a particular deployment of the web application is referring to.

All these pieces are put together by a provisioner that deploys the final product on web servers that are run by nginx.

Please, have a look at our _Terraform_ infrastructure [definition](https://github.com/opentargets/terraform-google-opentargets-platform), on which we'll be releasing a blog post soon.

**Comment by romanhaa** [comment]
I understand. However, I think providing instructions on how to host the application from a Docker image might be useful for others that are not planning to use Terraform.

**Comment by mbdebian** [comment]
> I understand. However, I think providing instructions on how to host the application from a Docker image might be useful for others that are not planning to use Terraform.

I understand, but the web application would not work as intended, because it would lack the the data binding and customization profile and, having the Dockerfile and documentation update integrated in our master branch, would commit ourselves to support that way of running the web application.

@JarrodBaker and @carcruz , what are your views on this?

**Comment by fedde-s** [comment]
This Dockerfile is technically already compatible with the configuration profiles and linking settings; we are actively using them and have been with the Dockerfiles we previously maintained in the [opentargets/platform-app](https://github.com/opentargets/platform-app/) and [opentargets/genetics-app](https://github.com/opentargets/genetics-app/) repositories. Perhaps it would have been a more complete proposal if we'd first worked on more explicitly documenting how to use them in a `docker run` command, perhaps even using a more deployer-friendly entrypoint script that's effectively a slimmed-down version of relevant parts of the Terraform setup.

**Pull request closed without merging**
