### PR TITLE
[Genetics]: fix README logos

### PR DESCRIPTION
**Pull request by raskolnikov-rodion**
## Description

Fix paths and alts for logos in the README file of the Genetics app.

Before:
image

After:
image

**Issue:** https://github.com/opentargets/ot-ui-apps/issues/261

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

You can visualize [here](https://github.com/raskolnikov-rodion/ot-ui-apps/tree/fix/docs-imgs/apps/genetics#special-thanks) the new version of the README file, correctly displaying the logos.

### CODE REVIEW

**Comment by raskolnikov-rodion** [comment]
Hello @carcruz and @chinmehta!

I just learned about the Open Targets projects and decided to drop in a small contribution to get started. I moved the logos to the root of the repository to avoid duplication, since they are being used in both apps. If you believe a different kind of organization would be better suited to the project, please let me know and I'll make the necessary changes 🙂

**Comment by carcruz** [comment]
Hello @raskolnikov-rodion, thanks for your PR. 
Since most of this documentation is outdated, we need to delete most of this and re-write it again. 

I recommend you help us with the typescript refactor that is ongoing. [Here you can find more details](https://github.com/opentargets/issues/issues/2871). We aim to replace all JS code with TS. We look for small PRs (1 per file) and we usually review them in ~1 week.

**Comment by raskolnikov-rodion** [comment]
@carcruz sounds good, I'll check it out. Thanks for the review!

**Comment by carcruz** [comment]
> @carcruz sounds good, I'll check it out. Thanks for the review!

Thanks a lot, please let me know if you need any help or guidance. carlos_cruz@ebi.ac.uk

**Pull request closed without merging**
