### PR TITLE
[Genetics] Refactor both `Page` components to TS

### PR DESCRIPTION
**Pull request by riyavsinha**
@carcruz is there a way to remove one of these? They end up being identical in styling and HTML.

There is some repetition between `components` and `ot-ui-components` (e.g. link also). What is the purpose of `ot-ui-components`?

## Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

**Issue:** #[2871](https://github.com/opentargets/issues/issues/2871)
**Deploy preview:** (link)

## Type of change

TS Refactor

## How Has This Been Tested?

Manual, still compiles and runs

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by chinmehta** [comment]
Hey, Thanks for bringing this forward as it helps us maintain a more organized code.

`components` is folder inside each application that are specific to them. `ot-ui-components` is a shared package.

We are currently in process of moving similar components from both application like you mentioned to `ot-ui-apps\packages\ui\src`. This folder will serve as a repository for files that are commonly accessed and shared by both applications.

For better understanding, I would take a quick look at `ot-ui-apps\packages\ui\src\LongText.tsx` or `ot-ui-apps\packages\ui\src\Link.tsx ` and then exporting them from `ot-ui-apps\packages\ui\src\index.tsx`.

If you have any additional suggestions or concerns, please feel free to share them.

**Comment by riyavsinha** [comment]
Thanks for the explanation Chintan! That sounds great.

Given that, what changes do I need to make to my PR for now?

**Comment by chinmehta** [comment]
Below are general steps for moving a comp into ui package.

1. Create a new component named `Page.tsx` in the path `ot-ui-apps\packages\ui\src` . 
2. Check what is different between both component and try to create a common component can be used in both.
3. If it has some different data then pass it as props, if different style then and boolean props (this case will fit) or it has some api calls then create a context to resolve it.
4. Import this component and check on both apps if it is working as expected.
5. Check all the places it has been used(not in this case).
6. Delete the old component.

Please let me know if i can provide further explanation .

**Comment by chinmehta** [comment]
Hey, 
While working on this [issue-2903](https://github.com/opentargets/issues/issues/2903), we required to make changes in page.tsx. But unfortunately due to conflict, we were not able to merge this before start working. 

But on the bright side we worked on it as planned and moved ``Page.tsx`` to UI package and importing it in both applications.
Here is the link you can check for the new file, we have added a new folder ``Pages`` in ui. 
https://github.com/opentargets/ot-ui-apps/pull/156/files .

I think if you could update all the PR's with latest main, we will be good to review it after upcoming release. 

Please let me know if i can help with anything.

**Pull request closed without merging**
